apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - image.rallypoint.tech
      secretName: image-tls
  rules:
    - host: image.rallypoint.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}-clusteip
              servicePort: 8888
