apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-clusteip
  labels:
    app: {{ .Chart.Name }}-clusteip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
